name: Build
on:
  push:
    branches:
      ["main"]
  pull_request:
    types: [opened, synchronize, reopened]
jobs:

  OWASP_Dependency_Check:
    name: OWASP Dependency Check
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: 'Prueba'
          path: '.'
          format: 'HTML'    
          args: >
            --failOnCVSS 7
            --enableRetired
            
      - name: Upload Test results
        uses: actions/upload-artifact@master
        with:
          name: Depcheck report
          path: ${{github.workspace}}/reports 
  
  DeployToProduction:
    name: DeployToProduction
    needs: OWASP_Dependency_Check
    runs-on: ubuntu-latest
    steps:
      - name: Test1
        run: echo 'Test1'

          
  ZAP_Scan:
    needs: DeployToProduction
    name: ZAP Scan
    runs-on: ubuntu-latest
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.5.0
        with:
          target: ${{ secrets.SERVER_WEB }}          
